[build]
  builder = "NIXPACKS"

[deploy]
  numReplicas = 1
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3
  
[healthcheck]
  endpoint = "/"
  interval = 30
  timeout = 10
  retries = 3