[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run server"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
PORT = "$PORT"